language: python
python:
 - "2.7"

install: "pip install -r requirements.txt"

before_script:
 - autopep8 -ir *.py
 - flake8 --max-complexity=10 --exclude=*.txt,*.md --max-line-length=200 *.py

script:
 - lettuce test
 - python test_commission.py -v
 - coverage run --branch test_commission.py
 - coverage report -m
